### ISSUE TITLE
Incorrect reporting of service status in failed state

### ISSUE THREAD

**Issue by nikever** [sighupio/fury-connect-switch#33]
Hello,

when a service is in a failed state, as the Boundary service in the following picture:

![image](https://user-images.githubusercontent.com/6024049/129710438-e0424c88-62c3-4e26-a25f-abb70f24f92c.png)

and I try to start the service via the button, the service is reported as active while, in reality, it is still in a failed state:

![image](https://user-images.githubusercontent.com/6024049/129710821-890064cf-6b54-4a4d-9850-3eb90ff196f0.png)

**Comment by Al-Pragliola** [comment]
Working on it!
